### ISSUE TITLE
Register main models in Django Admin

### ISSUE THREAD

**Issue by DmytroLitvinov** [AleksandrZhukovin/DjangoBlog#10]
https://github.com/AleksandrZhukovin/DjangoBlog/blob/7c81f5b0ed749f8ee34ef95f9ae704c59facef23/blog/admin.py#L3

It will give you possibility to overview instance via web UI instead of shell for example. Django Admin is a cool application. Read about it more.

**Comment by AleksandrZhukovin** [comment]
@DmytroLitvinov, I read about admin UI and that I can register some models I want to edit using web UI, but I don`t think there are models in this project to manage with admin UI, all of them are connected personaly to user, so I don`t know what admin can do with them.

**Comment by DmytroLitvinov** [comment]
@AleksandrZhukovin , it is just for practicing ;) 
Discover for Django Admin provide and register it and try to look what it provides you. Django admin is commonly used by developers to get access to data or by clients (not technical staff)
