### ISSUE TITLE
migrations for 'blog' are missed

### ISSUE THREAD

**Issue by DmytroLitvinov** [AleksandrZhukovin/DjangoBlog#13]
When I tried to run project locally, it raises an issue there is table 'blog_topic'
So I see migrations are not created and I can't apply migrations to create that table in database.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/16066485/227267419-df55e4bb-9e02-4d91-bcd1-cc2acc3ccdf2.png">

**Comment by AleksandrZhukovin** [comment]
Am I right that I shouldn`t push migrations dir an database file? So you have to make migrations localy before launch server?

**Comment by DmytroLitvinov** [comment]
@AleksandrZhukovin , no, you should push your migrations to repository so everybody can apply them to modify DB changes.
